services:
    _defaults:
        autowire: true
        autoconfigure: true

    CategoryBundle\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'