version: '3.8'

services:
  php:
    build: .
    container_name: symfony_php
    volumes:
      - ./app:/var/www/html
    env_file:
      - app/.env
    ports:
      - "9000:9000"
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bookstore
      MYSQL_USER: app
      MYSQL_PASSWORD: apppass
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password